import type { Metadata } from "next";
import RegisterForm from "@/components/form/register-form";

export const metadata: Metadata = {
  title: "Register | MyWorkshop",
  description: "Generated by create next app",
};

export default function RegisterPage() {
  return (
    <section className="flex flex-col gap-2 bg-white m-4 p-16 rounded-2xl">
      <div className="flex flex-col gap-4 w-full max-w-md h-full">
        <div className="flex flex-col text-left">
          <h1 className="font-bold text-5xl">Registration Form</h1>
        </div>
        <RegisterForm />
      </div>
    </section>
  );
}
