import "@/app/globals.css";

import type { Metadata } from "next";
import Sidemenu from "@/components/navigation/sidemenu";

export const metadata: Metadata = {
  title: "Main | MyWorkshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-neutral-900 py-6 pr-6 w-dvw h-dvh overflow-y-hidden text-white">
        <div className="flex w-full h-full">
          <Sidemenu />
          <section className="bg-white rounded-4xl w-full h-full text-neutral-800 transition-all duration-200">
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
