import "@/app/globals.css";

import type { Metadata } from "next";
import Sidemenu from "@/components/navigation/sidemenu";

export const metadata: Metadata = {
  title: "Main | MyWorkshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-dvh w-dvw overflow-y-hidden bg-neutral-900 py-6 pr-6 text-white">
        <div className="root flex h-full w-full">
          <Sidemenu />
          <section className="h-full w-full rounded-4xl bg-white text-neutral-800 transition-all duration-200">
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
