import LoginForm from "@/components/form/login-form";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login | MyWorkshop",
  description: "Generated by create next app",
};

export default function LoginPage() {
  return (
    <section className="flex flex-col gap-2 bg-white m-4 p-16 rounded-2xl">
      <div className="flex flex-col gap-8 w-full max-w-md h-full">
        <div className="flex flex-col text-left">
          <h1 className="font-bold text-5xl">Welcome Back!</h1>
          <span className="text-neutral-500">
            Log In to manage your work pipelines with ease.
          </span>
        </div>
        <LoginForm />
      </div>
    </section>
  );
}
