import {
  CalendarIcon,
  KanbanIcon,
  ListIcon,
  TableIcon,
} from "@/components/view/view-icons";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import Breadcrumbs from "@/components/ui/breadcrubs";
import FilterTasksButton from "@/components/view/filter-button";
import { KanbanViewBoard } from "@/components/kanban/kanban";
import ListView from "@/components/list/listView";
import { Metadata } from "next";
import TabsTriggerButton from "@/components/view/tabs-trigger";
import ViewNewTaskButton from "@/components/view/new-task-button";

export const metadata: Metadata = {
  title: "Pipelines | MyWorkshop",
  description: "Generated by create next app",
};

export default function WorkshopPage() {
  return (
    <div className="flex gap-8 h-full">
      <div className="flex flex-col px-8 py-8 w-full overflow-x-hidden">
        <div>
          <Breadcrumbs />
          <hr />
        </div>
        <div className="flex flex-col gap-2">
          <h1 className="mt-8 font-bold text-3xl">PIPELINE TITLE </h1>
        </div>
        <div className="flex gap-8 w-full overflow-auto">
          <Tabs defaultValue="kanban" className="w-full">
            <div className="top-0 sticky flex justify-between items-end bg-white border-b border-b-neutral-200 w-full">
              <TabsList className="bg-transparent p-0 rounded-none">
                <TabsTriggerButton
                  label="Kanban"
                  value="kanban"
                  leadingIcon={<KanbanIcon />}
                />
                <TabsTriggerButton
                  label="List"
                  value="list"
                  leadingIcon={<ListIcon />}
                />
              </TabsList>
              <div className="flex items-center gap-2 pb-4">
                <FilterTasksButton />
                <ViewNewTaskButton />
              </div>
            </div>
            <div className="mt-4">
              <TabsContent value="kanban">
                <KanbanViewBoard />
              </TabsContent>
              <TabsContent value="list">
                <ListView />
              </TabsContent>
            </div>
          </Tabs>
        </div>
      </div>
      {/* <PipelineSidemenu /> */}
    </div>
  );
}
