import { QueryUserPipelines } from "@/actions/tasks/query-user-pipelines";
import NewPipelineForm from "@/components/form/new-pipeline-form";
import Popover from "@/components/popover/popover";
import Breadcrumbs from "@/components/ui/breadcrubs";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Pipelines | MyWorkshop",
  description: "Generated by create next app",
};

export default async function WorkshopPage() {
  const pipelines = await QueryUserPipelines();
  // TODO: Handle Unauthorized and Non-existent pipelines.

  return (
    <div className="flex gap-8 h-full">
      <div className="flex flex-col gap-4 py-8 w-full overflow-x-hidden">
        <div className="px-8">
          <Breadcrumbs />
          <hr />
        </div>
        <div className="flex flex-col gap-4 px-8 py-4 overflow-auto">
          {pipelines ? (
            pipelines.map((pipelines) => {
              return (
                <Link
                  href={`/workshop/pipelines/${pipelines.id}`}
                  key={pipelines.id}
                  className="flex shadow-sm p-6 border border-neutral-200 rounded-2xl"
                >
                  <span>{pipelines.title}</span>
                </Link>
              );
            })
          ) : (
            <span>No Pipelines were found. Create a New one!</span>
          )}
        </div>
        <div className="flex px-8">
          <Popover
            render={<div className="btn btn-neutral">Add Pipeline</div>}
            contents={<NewPipelineForm />}
            align="start"
            side="bottom"
            disposeOnButtonClick={false}
          />
        </div>
      </div>
    </div>
  );
}
