import Breadcrumbs from "@/components/ui/breadcrubs";
import { KanbanDynamicOverlayDemo } from "@/components/kanban/demo";
import KanbanSidemenu from "../../../../components/kanban/pipeline-sidemenu";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pipelines | MyWorkshop",
  description: "Generated by create next app",
};

export default function WorkshopPage() {
  return (
    <div className="flex gap-8 h-full">
      <div className="py-8 w-full overflow-x-hidden">
        <div className="px-8">
          <Breadcrumbs />
          <hr />
        </div>
        <div className="flex gap-8 px-8 overflow-auto">
          <span>A list of Pipelines goes here.</span>
        </div>
      </div>
      <KanbanSidemenu />
    </div>
  );
}
